apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-queues
  namespace: default
data:
    sharing-code-instructions: "sharing-code-instructions"
    demo-insert-instructions: "demo-insert-instructions"
    demo-download-instructions: "demo-download-instructions"
    demo-obtain-reports: "demo-obtain-reports"
    manual-demo-download-reports: "manual-demo-download-reports"

    demo-analyze-instructions: "demo-analyze-instructions"
    demo-analyze-reports: "demo-analyze-reports"

    demos-fanout-exchange: "demos-fanout-exchange"

    demos-SO: "demos-SO"

    matches-dbi: "matches-dbi"
