apiVersion: v1
kind: Pod
metadata:
  name: httpie-debug
  labels:
    app: httpie
    debug: "true"
spec:
  containers:
    - name: httpie
      image: alpine/httpie
      command: ["/bin/sh", "-ec", "sleep 1000"]
