apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-central 
    namespace: testing
spec:
    replicas: 1
    selector:
        matchLabels:
            app: demo-central 
    template:
        metadata:
            labels:
                app: demo-central 
        spec:
            containers:
                - image: mentorgg.azurecr.io/democentral:2.2.2-pre
                  name: main
                  imagePullPolicy: Always

                  resources:
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits:
                      cpu: 200m
                      memory: 256Mi

                  ports:
                      - containerPort: 80
                  env:

                      - name: MOCK_SUBSCRIPTION_LOADER
                        value: "True"

                      - name: MYSQL_CONNECTION_STRING
                        value: "server=mentorgg-mysql.mysql.database.azure.com;port=3306;userid=testing@mentorgg-mysql;password=mentorgg;database=t_democentral;"

                      - name: MENTORINTERFACE_BASE_ADDRESS
                        value: "mock"

                      - name: MATCHRETRIEVER_BASE_ADDRESS
                        value: "http://match-retriever"

                      - name: AMQP_MATCHWRITER_INSERTION
                        valueFrom:
                             configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-fanout-exchange

                      - name: AMQP_MATCHWRITER_INSERTION_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: matches-dbi

                        # ===

                      - name: AMQP_MANUALDEMODOWNLOAD
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: manual-demo-download-reports

                      - name: AMQP_DEMODOWNLOADER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-download-instructions

                      - name: AMQP_DEMODOWNLOADER_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-obtain-reports

                        # ===

                      - name: AMQP_DEMOFILEWORKER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-analyze-instructions

                      - name: AMQP_DEMOFILEWORKER_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-analyze-reports

                        # ===

                      - name: AMQP_GATHERER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-insert-instructions

                        # ===

                      - name: AMQP_SITUATION_OPERATOR
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-so-instructions

                      - name: AMQP_SITUATION_OPERATOR_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-so-reports

                        # ===

                      - name: AMQP_MATCHWRITER_DEMO_REMOVAL
                        value: TEMP

                      - name: AMQP_MATCHWRITER_DEMO_REMOVAL_REPLY
                        value: TEMP

                        # ===

                      - name: BLOBSTORAGE_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: blob-storage
                                key: connection-string

                      - name: AMQP_URI
                        value: "amqp://user:mentorgg@rabbitmq-headless:5672"

                      - name: REDIS_CONFIGURATION_STRING
                        value: "testing-match-data-redis:6379,password=mentorgg"

                      - name: DEMO_REMOVAL_INTERVAL
                        value: "2"

                      - name: DEMO_REMOVAL_ALLOWANCE
                        value: "1"
---
apiVersion: v1
kind: Service
metadata:
    name: demo-central
    namespace: testing
spec:
    selector:
        app: demo-central
    ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 80
