apiVersion: apps/v1
kind: Deployment
metadata:
    name: match-writer
    namespace: testing
spec:
    replicas: 1
    selector:
        matchLabels:
            app: match-writer
    template:
        metadata:
            labels:
                app: match-writer
        spec:
            nodeSelector:
                nodeType: memory
            containers:
                - image: mentorgg.azurecr.io/matchwriter:2.0.1
                  name: main
                  imagePullPolicy: Always

                  resources:
                    requests:
                      cpu: 300m
                      memory: 700Mi
                    limits:
                      cpu: 600m
                      memory: 1024Mi

                  ports:
                    - containerPort: 80
                  env:

                      - name: AMQP_INSERTION_INSTRUCTIONS
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-insertion-instructions

                      - name: AMQP_INSERTION_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-insertion-reports

                      - name: AMQP_DEMOCENTRAL_DEMO_REMOVAL
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: match-removal-instructions

                      - name: AMQP_DEMOCENTRAL_DEMO_REMOVAL_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: match-removal-reports

                      - name: AMQP_URI
                        value: "amqp://user:mentorgg@rabbitmq-headless:5672"                     

                      - name: AMQP_PREFETCH_COUNT
                        value: "2"

                      - name: REDIS_CONFIGURATION_STRING
                        value: "testing-match-data-redis:6379,password=mentorgg"

                      - name: MYSQL_CONNECTION_STRING
                        value: "server=mentorgg-mysql.mysql.database.azure.com;port=3306;userid=testing@mentorgg-mysql;password=mentorgg;database=t_matchdata;"
---
apiVersion: v1
kind: Service
metadata:
    name: match-writer
    namespace: testing
spec:
    selector:
        app: match-writer
    ports:
        - protocol: TCP
          name: public
          port: 80
          targetPort: 80
