apiVersion: apps/v1
kind: Deployment
metadata:
    name: faceit-match-gatherer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: faceit-match-gatherer
    template:
        metadata:
            labels:
                app: faceit-match-gatherer
        spec:
            containers:
                - image: mentorgg.azurecr.io/faceitmatchgatherer:0.1.0
                  name: main
                  ports:
                      - containerPort: 80
                  env:
                      - name: STEAM_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: steam-api
                                key: key

                      - name: MYSQL_CONNECTIONSTRING
                        value: "server=users-mysql.default.svc.cluster.local;port=3306;userid=mentorinterface;password=mentorgg;database=users;"
---
apiVersion: v1
kind: Service
metadata:
    name: faceit-match-gatherer
spec:
    selector:
        app: faceit-match-gatherer
    ports:
        - protocol: TCP
          name: public
          port: 80
          targetPort: 80
