apiVersion: apps/v1
kind: Deployment
metadata:
    name: match-writer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: match-writer
    template:
        metadata:
            labels:
                app: match-writer
        spec:
            containers:
                - image: mentorgg.azurecr.io/matchwriter:0.4.6
                  name: main

                  resources:
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits:
                      cpu: 200m
                      memory: 128Mi

                  ports:
                    - containerPort: 80
                  env:

                      - name: AMQP_EXCHANGE_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-fanout-exchange

                      - name: AMQP_EXCHANGE_CONSUME_QUEUE
                        value: "central-match-writer"

                      - name: AMQP_CALLBACK_QUEUE
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: matches-dbi

                      - name: AMQP_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq
                                key: rabbitmq-password
                      - name: AMQP_URI
                        value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq-headless:5672"
                     
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: match-data-sets-redis
                                key: redis-password
                      - name: REDIS_URI
                        value: "match-data-sets-redis-master:6379,password=$(REDIS_PASSWORD)"

                      - name: MYSQL_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: match-data-mysql
                              key: mysql-password
                      - name: MYSQL_CONNECTION_STRING
                        value: "server=match-data-mysql;port=3306;userid=matchdata;password=$(MYSQL_PASSWORD);database=data;"
---
apiVersion: v1
kind: Service
metadata:
    name: match-writer
spec:
    selector:
        app: match-writer
    ports:
        - protocol: TCP
          name: public
          port: 80
          targetPort: 80
