apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-central 
spec:
    replicas: 1
    selector:
        matchLabels:
            app: demo-central 
    template:
        metadata:
            labels:
                app: demo-central 
        spec:
            containers:
                - image: mentorgg.azurecr.io/democentral:0.2.1-pre
                  name: main
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  env:
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: demo-central-mysql
                                key: mysql-password

                      - name: MYSQL_CONNECTION_STRING
                        value: "server=demo-central-mysql;port=3306;userid=democentral;password=$(MYSQL_PASSWORD);database=demoinfo"

                      - name: HTTP_USER_SUBSCRIPTION
                        value: "https://mentor-interface"


                      - name: AMQP_MANUALDEMODOWNLOAD
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-manual-internal-urls

                      - name: AMQP_DEMODOWNLOADER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-download-urls

                      - name: AMQP_DEMODOWNLOADER_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-internal-urls

                      - name: AMQP_DEMOFILEWORKER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-DFW

                      - name: AMQP_DEMOFILEWORKER_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-DFW-reply

                      - name: AMQP_GATHERER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-gatherer

                      - name: AMQP_SITUATIONSOPERATOR
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-SO

                      - name: AMQP_MATCHDBI
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: matches-dbi


                      - name: AMQP_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq
                                key: rabbitmq-password
                      - name: AMQP_URI
                        value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq-headless:5672"
---
apiVersion: v1
kind: Service
metadata:
    name: demo-central
spec:
    selector:
        app: demo-central
    ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 80
