apiVersion: apps/v1
kind: Deployment
metadata:
    name: situation-operator
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: situation-operator
    template:
        metadata:
            labels:
                app: situation-operator
        spec:

            volumes:
                - name: subscription-configuration-volume
                  configMap:
                      name: user-subscription-configuration
                      items:
                          - key: data.json
                            path: subscriptions.json
                            
            nodeSelector:
                nodeType: memory

            containers:
                - image: mentorgg.azurecr.io/situationoperator:0.2.3
                  name: main

                  volumeMounts:
                      - name: subscription-configuration-volume
                        mountPath: /app/config

                  resources:
                    requests:
                      cpu: 100m
                      memory: 500Mi
                    limits:
                      cpu: 200m
                      memory: 700Mi

                  ports:
                    - containerPort: 80
                  env:

                      - name: AMQP_EXTRACTION_INSTRUCTIONS
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-extraction-instructions

                      - name: AMQP_EXTRACTION_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demos-extraction-reports

                      # ---

                      - name: AMQP_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq
                                key: rabbitmq-password
                     
                      - name: AMQP_URI
                        value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq-headless:5672"           

                      - name: AMQP_PREFETCH_COUNT
                        value: "2"

                      # ---

                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: match-data-sets-redis
                                key: redis-password
                                
                      - name: REDIS_CONFIGURATION_STRING
                        value: "match-data-sets-redis-master:6379,password=$(REDIS_PASSWORD)"

                      # ---

                      - name: MYSQL_PASSWORD
                        valueFrom:
                          secretKeyRef:
                              name: situation-operator-mysql
                              key: mysql-password

                      - name: MYSQL_CONNECTION_STRING
                        value: "server=mentorgg-mysql.mysql.database.azure.com;port=3306;userid=situationoperator@mentorgg-mysql;password=$(MYSQL_PASSWORD);database=situationoperator;"
---
apiVersion: v1
kind: Service
metadata:
    name: situation-operator
    namespace: default
spec:
    selector:
        app: situation-operator
    ports:
        - protocol: TCP
          name: public
          port: 80
          targetPort: 80
