apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer 
metadata:
    name: monitoring-letsencrypt-issuer
spec:
    acme:
        email: dev@mentor.gg
        privateKeySecretRef:
            name: monitoring-letsencrypt-key
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - http01:
                ingress:
                  class:  nginx
