apiVersion: v1
kind: Service
metadata:
    name: internal-rabbit
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    labels:
        app: rabbitmq
        app.kubernetes.io/part-of: steamworksconnection

    namespace: default
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - port: 5672
