apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-file-worker 
spec:
    replicas: 5
    selector:
        matchLabels:
            app: demo-file-worker 
    template:
        metadata:
            labels:
                app: demo-file-worker 
        spec:
            containers:
                - image: mentorgg.azurecr.io/demofileworker:2.1.3
                  name: main

                  resources:
                    requests:
                      cpu: 400m
                      memory: 500Mi
                    limits:
                      cpu: 700m
                      memory: 700Mi

                  ports:
                      - containerPort: 80

                  env:
                      - name: TEMPORARY_FOLDER_LOCATION
                        value: "/tmp"

                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: match-data-sets-redis
                                key: redis-password
                                
                      - name: REDIS_CONFIGURATION_STRING
                        value: "match-data-sets-redis-master:6379,password=$(REDIS_PASSWORD)"
 
                        # Set the Redis Expiry time to 1hr
                      - name: REDIS_EXPIRATION_TIME
                        value: "1"

                      - name: DEMO_CENTRAL_BASE_URI
                        value: "http://demo-central"

                      - name: AMQP_DEMOCENTRAL
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-analyze-instructions

                      - name: AMQP_DEMOCENTRAL_REPLY
                        valueFrom:
                            configMapKeyRef:
                                name: rabbitmq-queues
                                key: demo-analyze-reports

                      - name: AMQP_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq
                                key: rabbitmq-password
                      
                      - name: AMQP_URI
                        value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq-headless:5672"
                      
                      - name: AMQP_PREFETCH_COUNT
                        value: "1"
---
apiVersion: v1
kind: Service
metadata:
    name: demo-file-worker
spec:
    selector:
        app: demo-file-worker
    ports:
        - protocol: TCP
          name: http
          port: 80
          targetPort: 80
