apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: users-pvc
spec:
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
