apiVersion: v1
kind: Secret
metadata:
  name: faceit-api
type: Opaque
stringData:
  client-secret: B0lrTJDUHeMnqZvQOMbb47vKcErJdCSqbaR2PV53
  client-id: 98dfbe01-bc76-4148-90f0-a9221c963a9f
  api-key: 2598fd84-19b4-4770-86c6-36e7cbcc4dac
