apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: upload-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "upload-letsencrypt-issuer"

    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, OPTIONS"

    nginx.ingress.kubernetes.io/cors-allow-origin: "https://mentor.gg"

    nginx.ingress.kubernetes.io/proxy-body-size: "900m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  tls:
  - hosts:
    - upload.mentor.gg
    secretName: upload-letsencrypt-key
  rules:
  - host: upload.mentor.gg
    http:
      paths:
      - path: /
        backend:
          serviceName: manual-demo-downloader
          servicePort: 80
